Repository Automattic/Gravatar-SDK-iOS, pull requests merged in 2024-10, with the labels that each got.

#432 QE OAuth: Ignore the cancelled error so it doesn't override our current error
  Sources/GravatarUI/SwiftUI/OAuthSession/OAuthSession.swift
  Sources/GravatarUI/SwiftUI/ProfileEditor/QuickEditor.swift
Labels: enhancement

#442 Set "Accept : application/json" header
  Sources/Gravatar/Network/Services/URLSessionHTTPClient.swift
Labels: enhancement

#445 Add color scheme picker to the SwiftUI demo app
  Demo/Demo/Gravatar-SwiftUI-Demo/DemoAvatarPickerView.swift
  Demo/Demo/Gravatar-SwiftUI-Demo/DemoProfileEditorView.swift
  Demo/Demo/Gravatar-SwiftUI-Demo/QEColorSchemePickerRow.swift
  Demo/Gravatar-Demo.xcodeproj/project.pbxproj
Labels: enhancement

#455 Add common headers for Platform, SDK version, Source app
  Gravatar.podspec
  Package.swift
  Sources/Gravatar/Bundle+ResourceBundle.swift
  Sources/Gravatar/BundleInfo.swift
  Sources/Gravatar/Network/Services/AvatarService.swift
  Sources/Gravatar/Network/Services/URLSessionHTTPClient.swift
  Sources/Gravatar/Resources/SDKInfo.plist
  Tests/GravatarTests/AvatarServiceTests.swift
Labels: enhancement

#460 Prevent stacking of toast messages
  Sources/GravatarUI/Resources/en.lproj/Localizable.strings
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerViewModel.swift
  Sources/GravatarUI/SwiftUI/Toast/Toast.swift
  Sources/GravatarUI/SwiftUI/Toast/ToastManager.swift
Labels: enhancement

#468 Update strings in base locale
  Sources/GravatarUI/Resources/en.lproj/Localizable.strings
Labels: Localization

#482 Make HTTPClient internal
  Sources/Gravatar/Network/Services/AvatarService.swift
  Sources/Gravatar/Network/Services/CheckTokenAuthorizationService.swift
  Sources/Gravatar/Network/Services/HTTPClient.swift
  Sources/Gravatar/Network/Services/ImageDownloadService.swift
  Sources/Gravatar/Network/Services/ImageUploadService.swift
  Sources/Gravatar/Network/Services/ProfileService.swift
  Sources/Gravatar/Network/URLSessionProtocol.swift
  Sources/TestHelpers/HTTPClientMock.swift
  Sources/TestHelpers/ImageDownloadService+Extension.swift
  Tests/GravatarTests/AvatarServiceTests.swift
  Tests/GravatarTests/ImageDownloadServiceTests.swift
  Tests/GravatarTests/ProfileServiceTests.swift
  Tests/GravatarUITests/OAuthSessionTests.swift
  Tests/GravatarUITests/ProfileViewModelTests.swift
Labels: Tech Debt

#484 Fix podspec publishing
  .buildkite/pipeline.yml
Labels: bug, tooling

#506 Add docs for AvatarView
  Sources/GravatarUI/GravatarUI.docc/AvatarViewArticle.md
  Sources/GravatarUI/GravatarUI.docc/GettingStarted.md
  Sources/GravatarUI/GravatarUI.docc/GravatarUI.md
Labels: documentation

#523 Update localizations
  Sources/GravatarUI/Resources/ar.lproj/Localizable.strings
  Sources/GravatarUI/Resources/he.lproj/Localizable.strings
  Sources/GravatarUI/Resources/ja.lproj/Localizable.strings
  Sources/GravatarUI/Resources/zh-Hant.lproj/Localizable.strings
Labels: Localization

#522 Simplify OpenAPI Generator
  .gitignore
  Makefile
  openapi/GravatarOpenAPIClient/.openapi-generator-ignore
  openapi/GravatarOpenAPIClient/.openapi-generator/FILES
  openapi/GravatarOpenAPIClient/.openapi-generator/VERSION
  openapi/openapi.yaml
  openapi/templates/model.mustache
  openapi/templates/modelInlineEnumDeclaration.mustache
  openapi/templates/modelObject.mustache
Labels: tooling, Tech Debt

#531 Remove the swiftlint plugin
  Package.swift
Labels: CI/CD

#529 Release/3.0.0
  Demo/Demo/Gravatar-UIKit-Demo/DemoUploadImageViewController.swift
  Gravatar.podspec
  GravatarUI.podspec
  Package.swift
  README.md
  Sources/Gravatar/Cache/ImageCaching.swift
  Sources/Gravatar/Configuration.swift
  Sources/Gravatar/Identifiers/AvatarIdentifier.swift
  Sources/Gravatar/Network/Services/AvatarService.swift
  Sources/Gravatar/Network/Services/ImageUploadService.swift
  Sources/Gravatar/Options/AvatarQueryOptions.swift
  Sources/Gravatar/Options/AvatarSelection.swift
  Sources/Gravatar/Options/ImageDownloadOptions.swift
  Sources/Gravatar/Resources/SDKInfo.plist
  Sources/GravatarUI/GravatarCompatibleUI/UIImageView+Gravatar.swift
  Sources/GravatarUI/GravatarUI.docc/GravatarUI.md
  Sources/GravatarUI/GravatarUI.docc/Resources/QuickEditor_Tutorial/QuickEditor_Tutorial_01_03@2x.png
  Sources/GravatarUI/GravatarUI.docc/Resources/QuickEditor_Tutorial/QuickEditor_Tutorial_01_04@2x.png
  Sources/GravatarUI/GravatarUI.docc/Resources/QuickEditor_Tutorial/QuickEditor_Tutorial_01_05@2x.png
  Sources/GravatarUI/GravatarUI.docc/Resources/QuickEditor_Tutorial/QuickEditor_Tutorial_Header@2x.png
  Sources/GravatarUI/GravatarUI.docc/Resources/QuickEditor_Tutorial/QuickEditor_Tutorial_Preview@2x.png
  Sources/GravatarUI/GravatarUI.docc/Tutorials/QuickEditor/QE_Tut_01.swift
  Sources/GravatarUI/GravatarUI.docc/Tutorials/QuickEditor/QE_Tut_02.swift
  Sources/GravatarUI/GravatarUI.docc/Tutorials/QuickEditor/QE_Tut_03.swift
  Sources/GravatarUI/GravatarUI.docc/Tutorials/QuickEditor/QE_Tut_04.swift
  Sources/GravatarUI/GravatarUI.docc/Tutorials/QuickEditor/QE_Tut_05.swift
  Sources/GravatarUI/GravatarUI.docc/Tutorials/QuickEditor/QuickEditor.tutorial
  Sources/GravatarUI/GravatarUI.docc/Tutorials/Tutorials.tutorial
  Sources/GravatarUI/ProfileView/BaseProfileView.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerContentLayout.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerView.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerViewModel.swift
  Sources/GravatarUI/SwiftUI/OAuthSession/OAuthSession.swift
  Tests/GravatarTests/AvatarServiceTests.swift
  Tests/GravatarUITests/OAuthSessionTests.swift
  openapi/openapi.yaml
  version.rb
Labels: release

#534 [Tooling] Setting up Danger
  .buildkite/pipeline.yml
  .github/workflows/run-danger.yml
  Dangerfile
  Gemfile
  Gemfile.lock
Labels: CI/CD, tooling
