Repository Automattic/Gravatar-SDK-iOS, pull requests merged in 2024-08, with the labels that each got.

#348 [Tooling] Remove the 'Build Demos' step from CI pipeline
  .buildkite/commands/build-demos.sh
  .buildkite/pipeline.yml
  fastlane/Fastfile
Labels: CI/CD

#352 [Tooling] Prevent uploading Prototype Builds when there's no Pull Request
  .buildkite/pipeline.yml
Labels: tooling

#356 Setup Legacy Localization Support
  Demo/Demo/Localizations/en.lproj/Localizable.strings
  Demo/Gravatar-Demo.xcodeproj/project.pbxproj
  Makefile
  Package.swift
  Sources/GravatarUI/Base/String+Additions.swift
  Sources/GravatarUI/ProfileFields/Model/ClaimProfileModel.swift
  Sources/GravatarUI/ProfileFields/ProfileButtonBuilder.swift
  Sources/GravatarUI/Resources/en.lproj/Localizable.strings
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerProfileView.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerView.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/Views/CTAButtonView.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/Views/ContentLoadingErrorView.swift
  Sources/GravatarUI/SwiftUI/CachedAsyncImage.swift
  Sources/GravatarUI/SwiftUI/Toast/Toast.swift
  Sources/GravatarUI/SwiftUI/Toast/ToastContainerView.swift
  fastlane/Fastfile
  fastlane/lib/lanes/localization.rb
Labels: enhancement, UI Components
