Repository Automattic/Gravatar-SDK-iOS, pull requests merged in 2024-11, with the labels that each got.

#551 Clean up SwiftLint removal
  .swiftlint.yml
  Demo/Gravatar-Demo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
Labels: tooling, Tech Debt

#555 Adding script to modify access control of generated openapi types
  Makefile
  access-control-modifier.swift
Labels: tooling

#557 Adding unit tests ro AvatarGridModel and AvatarImageModel
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarGridModel.swift
  Tests/GravatarUITests/AvatarGridModelTests.swift
  Tests/GravatarUITests/AvatarImageModelTests.swift
Labels: Tech Debt

#558 Update to Xcode 16.1
  .buildkite/shared-pipeline-vars
  fastlane/Fastfile
Labels: CI/CD, tooling

#562 Update README.md with mention to Android repo
  README.md
Labels: documentation

#563 Deprecate `ProfileViewConfiguration.avatarConfiguration.borderColor` in favor of `Palette.avatar.border`
  Sources/GravatarUI/ProfileView/ProfileViewConfiguration.swift
Labels: Tech Debt

#561 Add a default `ProfileViewDelegate` conformance to `ProfileViewController
  Sources/GravatarUI/ProfileViewController/ProfileViewController.swift
Labels: enhancement, UI Components

#570 Add the initial avatar action menu [...]
  Sources/GravatarUI/Resources/Media.xcassets/more-horizontal.imageset/Contents.json
  Sources/GravatarUI/Resources/Media.xcassets/more-horizontal.imageset/more-horizontal.svg
  Sources/GravatarUI/Resources/en.lproj/Localizable.strings
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarAction.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerView.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/Views/AvatarGrid.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/Views/AvatarPickerAvatarView.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/Views/HorizontalAvatarGrid.swift
Labels: enhance, [Feature] Gravatar-QuickEditor, [Priority] Medium

#564 Adding tests for AvatarPickerViewModelTests
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerViewModel.swift
  Sources/TestHelpers/Bundle+ResourceBundle.swift
  Sources/TestHelpers/HTTPURLResponse+Extension.swift
  Sources/TestHelpers/Resources/Profiles/fullProfile.json
  Sources/TestHelpers/Resources/avatarSelected.json
  Sources/TestHelpers/Resources/avatarUploadResponse.json
  Sources/TestHelpers/Resources/avatarsResponse.json
  Tests/GravatarTests/Bundle+ResourceBundle.swift
  Tests/GravatarTests/ProfileServiceTests.swift
  Tests/GravatarUITests/AvatarPickerViewModelTests.swift
Labels: Tech Debt

#573 [Tooling] Update `Dangerfile` to run Rubocop with `bundle exec`
  Dangerfile
Labels: tooling

#565 Add (Apple Intelligence) image playground to the Quick Editor
  Demo/Gravatar-Demo.xcodeproj/project.pbxproj
  Sources/GravatarUI/Resources/en.lproj/Localizable.strings
  Sources/GravatarUI/SwiftUI/AvatarPicker/SystemImagePicker/SystemImagePickerView.swift
  Sources/GravatarUI/SwiftUI/View+Additions.swift
Labels: enhance, [Feature] Gravatar-QuickEditor, [Priority] Medium

#419 Image Squaring Stategy
  Sources/Gravatar/Extensions/UIImage.swift
  Sources/Gravatar/Network/Services/AvatarService.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerViewModel.swift
  Tests/GravatarTests/ImageSizeTests.swift
  Tests/GravatarTests/ImageSquaringTests.swift
  Tests/GravatarTests/UIImage+AdditionsTests.swift
Labels: enhance, [Feature] Gravatar-QuickEditor

#572 QE: Share image
  Demo/Gravatar-Demo.xcodeproj/project.pbxproj
  Sources/GravatarUI/Resources/en.lproj/Localizable.strings
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarAction.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarImageModel.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerView.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerViewModel.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarShareItem.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/Views/AvatarPickerAvatarView.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/Views/ShareSheet.swift
  Sources/GravatarUI/SwiftUI/View+Additions.swift
  Sources/TestHelpers/TestURLSessionError.swift
  Tests/GravatarUITests/AvatarPickerViewModelTests.swift
  Tests/GravatarUITests/TestImageFetcher.swift
Labels: enhance, [Feature] Gravatar-QuickEditor, [Priority] Medium

#576 Improve share sheet
  Sources/Gravatar/Extensions/UIImage+Additions.swift
  Sources/Gravatar/Extensions/UIImage+Square.swift
  Sources/GravatarUI/Resources/en.lproj/Localizable.strings
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerContentLayout.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerView.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerViewModel.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarShareItem.swift
  Tests/GravatarUITests/AvatarPickerViewModelTests.swift
Labels: enhance, [Feature] Gravatar-QuickEditor, [Priority] Medium

#574 Delete avatar
  Sources/Gravatar/Extensions/URL.swift
  Sources/Gravatar/Network/Services/AvatarService.swift
  Sources/Gravatar/Network/Services/CheckTokenAuthorizationService.swift
  Sources/Gravatar/Network/Services/HTTPClient.swift
  Sources/Gravatar/Network/Services/ImageDownloadService.swift
  Sources/Gravatar/Network/Services/ImageUploadService.swift
  Sources/Gravatar/Network/Services/ProfileService.swift
  Sources/Gravatar/Network/Services/URLSessionHTTPClient.swift
  Sources/GravatarUI/Resources/en.lproj/Localizable.strings
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarGridModel.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerView.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerViewModel.swift
  Tests/GravatarTests/URLSessionHTTPClientTests.swift
  Tests/GravatarUITests/AvatarGridModelTests.swift
Labels: enhance, [Feature] Gravatar-QuickEditor, [Priority] Medium

#577 Notify 3rd party when the selected avatar has been deleted
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarGridModel.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerView.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerViewModel.swift
Labels: [Feature] Gravatar-QuickEditor, [Priority] High

#575 Add playground option to the avatar menu
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarAction.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerView.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarShareItem.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/SystemImagePicker/CustomizableImageEditor.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/SystemImagePicker/ImagePlaygroundModifier.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/SystemImagePicker/SystemImagePickerView.swift
Labels: enhance, [Feature] Gravatar-QuickEditor, [Priority] Medium

#580 Implementing support for HTTPS scheme in oauth callback url for the demo app
  .configure
  .configure-files/Secrets.swift.enc
  Demo/Demo/Gravatar-Demo/SceneDelegate.swift
  Demo/Gravatar Demo.entitlements
  Demo/Gravatar-Demo.xcodeproj/project.pbxproj
Labels: enhance, demoapp

#583 Adding tests to avatar deletion flow
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarGridModel.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerViewModel.swift
  Sources/TestHelpers/HTTPURLResponse+Extension.swift
  Tests/GravatarUITests/AvatarPickerViewModelTests.swift
Labels: [Feature] Gravatar-QuickEditor
