Repository Automattic/Gravatar-SDK-iOS, pull requests merged in 2024-09, with the labels that each got.

#390 Add `SDKLocalizedString` global function
  .swiftlint.yml
  Demo/Gravatar-Demo.xcodeproj/project.pbxproj
  Demo/Gravatar-Demo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
  Sources/GravatarUI/ProfileFields/Model/ClaimProfileModel.swift
  Sources/GravatarUI/ProfileFields/ProfileButtonBuilder.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerProfileView.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerView.swift
  Sources/GravatarUI/Utility/SDKLocalizedString.swift
  fastlane/Fastfile
  fastlane/lanes/localization.rb
Labels: tooling, Localization

#387 Use `ImageCache.shared` as the default value
  Sources/Gravatar/Network/Services/ImageDownloadService.swift
  Tests/GravatarTests/AvatarServiceTests.swift
  Tests/GravatarTests/ImageDownloadServiceTests.swift
  version.rb
Labels: bug

#377 Quick Editor: Add presentation styles
  Demo/Demo/Gravatar-SwiftUI-Demo/DemoAvatarPickerView.swift
  Demo/Demo/Gravatar-SwiftUI-Demo/DemoProfileEditorView.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerContentLayout.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerView.swift
  Sources/GravatarUI/SwiftUI/AvatarPickerModalPresentationModifier.swift
  Sources/GravatarUI/SwiftUI/GravatarNavigationModifier.swift
  Sources/GravatarUI/SwiftUI/PreferenceKeys.swift
  Sources/GravatarUI/SwiftUI/ProfileEditor/QuickEditor.swift
  Sources/GravatarUI/SwiftUI/View+Additions.swift
Labels: enhancement

#396 Update wpmreleasetoolkit to 12.0
  Gemfile
  Gemfile.lock
Labels: CI/CD, tooling, Tech Debt

#386 Remove "async" from ImageCaching
  Sources/Gravatar/Cache/ImageCaching.swift
  Sources/Gravatar/Network/Services/ImageDownloadService.swift
  Sources/Gravatar/Network/Services/ImageDownloader.swift
  Sources/GravatarUI/GravatarCompatibleUI/UIImageView+Gravatar.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerViewModel.swift
  Sources/TestHelpers/TestImageCache.swift
  Tests/GravatarTests/AvatarServiceTests.swift
  Tests/GravatarTests/ImageDownloadServiceTests.swift
  Tests/GravatarUITests/TestImageFetcher.swift
Labels: Concurrency

#403 Fix DoCC generation for Github Pages
  .github/workflows/docc.yml
Labels: documentation, CI/CD

#409 Properly encode literal `+` characters in `URLQueryItem`s
  Sources/Gravatar/AvatarURL.swift
  Sources/Gravatar/URLComponents+Additions.swift
  Sources/GravatarUI/SwiftUI/OAuthSession/OAuthSession.swift
  Tests/GravatarTests/URLComponentsTests.swift
Labels: bug

#420 Show upload fail error dialog
  Sources/Gravatar/Network/APIErrorPayload.swift
  Sources/Gravatar/Network/Errors.swift
  Sources/Gravatar/Network/Services/AvatarService.swift
  Sources/Gravatar/Network/Services/URLSessionHTTPClient.swift
  Sources/GravatarUI/Resources/en.lproj/Localizable.strings
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarGridModel.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarImageModel.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerView.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerViewModel.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/Views/AvatarGrid.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/Views/AvatarPickerAvatarView.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/Views/DimmingButton.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/Views/HorizontalAvatarGrid.swift
  Tests/GravatarUITests/TestImageFetcher.swift
Labels: enhancement

#412 Merge Localizations
  Sources/GravatarUI/Resources/ar.lproj/Localizable.strings
  Sources/GravatarUI/Resources/de.lproj/Localizable.strings
  Sources/GravatarUI/Resources/es.lproj/Localizable.strings
  Sources/GravatarUI/Resources/fr.lproj/Localizable.strings
  Sources/GravatarUI/Resources/he.lproj/Localizable.strings
  Sources/GravatarUI/Resources/id.lproj/Localizable.strings
  Sources/GravatarUI/Resources/it.lproj/Localizable.strings
  Sources/GravatarUI/Resources/ja.lproj/Localizable.strings
  Sources/GravatarUI/Resources/ko.lproj/Localizable.strings
  Sources/GravatarUI/Resources/nl.lproj/Localizable.strings
  Sources/GravatarUI/Resources/pt-BR.lproj/Localizable.strings
  Sources/GravatarUI/Resources/ru.lproj/Localizable.strings
  Sources/GravatarUI/Resources/sv.lproj/Localizable.strings
  Sources/GravatarUI/Resources/tr.lproj/Localizable.strings
  Sources/GravatarUI/Resources/zh-Hans.lproj/Localizable.strings
  Sources/GravatarUI/Resources/zh-Hant.lproj/Localizable.strings
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerView.swift
Labels: Localization

#423 Use Implicit OAuth (token response)
  Sources/GravatarUI/SwiftUI/OAuthSession/AccessToken.swift
  Sources/GravatarUI/SwiftUI/OAuthSession/OAuthSession.swift
  Tests/GravatarUITests/AccessTokenTests.swift
Labels: enhancement

#427 Check if the correct user is authorized during OAuth
  Sources/Gravatar/Network/Services/CheckTokenAuthorizationService.swift
  Sources/Gravatar/Network/Services/ServiceConfig.swift
  Sources/GravatarUI/Resources/en.lproj/Localizable.strings
  Sources/GravatarUI/SwiftUI/OAuthSession/OAuthSession.swift
  Sources/GravatarUI/SwiftUI/ProfileEditor/QuickEditor.swift
Labels: enhancement

#429 Add content layout options to the demo app oauth page
  Demo/Demo/Gravatar-SwiftUI-Demo/DemoAvatarPickerView.swift
  Demo/Demo/Gravatar-SwiftUI-Demo/DemoProfileEditorView.swift
  Demo/Demo/Gravatar-SwiftUI-Demo/QEContentLayoutPickerRow.swift
  Demo/Demo/Gravatar-SwiftUI-Demo/QELayoutOptions.swift
  Demo/Gravatar-Demo.xcodeproj/project.pbxproj
Labels: enhancement

#430 Use a thread safe cache in TestImageCache to fix a crash
  Sources/TestHelpers/TestImageCache.swift
Labels: CI/CD

#435 Concurrency Improvements in ImageDownloadService
  Demo/Demo/Gravatar-UIKit-Demo/DemoUIImageViewExtensionViewController.swift
  Sources/Gravatar/Network/Services/ImageDownloadService.swift
  Sources/Gravatar/Network/Services/ImageDownloader.swift
  Sources/GravatarUI/GravatarCompatibleUI/UIImageView+Gravatar.swift
  Sources/TestHelpers/TestImageCache.swift
  Sources/TestHelpers/URLSessionMock.swift
  Tests/GravatarTests/ImageDownloadServiceTests.swift
  Tests/GravatarUITests/GravatarWrapper+UIImageViewTests.swift
Labels: bug, Concurrency
