Repository Automattic/Gravatar-SDK-iOS, pull requests merged in 2024-04, with the labels that each got.

#182 Merge `release/1.0.0-improvements` to `trunk`: Fix CI automation for publishing pods
  .buildkite/shared-pipeline-vars
Labels: CI/CD

#183 Adding `LargeProfileSummaryView`
  Demo/Demo/Gravatar-Demo/DemoLargeProfileViewController.swift
  Sources/GravatarUI/ProfileFields/PersonalInfoField.swift
  Sources/GravatarUI/ProfileView/LargeProfileSummaryView.swift
  Tests/GravatarUITests/LargeProfileSummaryViewTests.swift
  Tests/GravatarUITests/__Snapshots__/LargeProfileSummaryViewTests/testLargeProfileSummaryView.Dark.png
  Tests/GravatarUITests/__Snapshots__/LargeProfileSummaryViewTests/testLargeProfileSummaryView.Light.png
Labels: UI Components

#188 Adding `ProfileSummaryView`
  Demo/Demo/Gravatar-Demo/DemoLargeProfileViewController.swift
  Sources/GravatarUI/Configurator/Configurators.swift
  Sources/GravatarUI/ProfileFields/ProfileButtonBuilder.swift
  Sources/GravatarUI/ProfileView/ProfileComponentView.swift
  Sources/GravatarUI/ProfileView/ProfileSummaryView.swift
  Sources/GravatarUI/ProfileView/ProfileView.swift
  Tests/GravatarUITests/ProfileSummaryViewTests.swift
  Tests/GravatarUITests/__Snapshots__/ProfileSummaryViewTests/testProfileSummaryView.dark.png
  Tests/GravatarUITests/__Snapshots__/ProfileSummaryViewTests/testProfileSummaryView.light.png
Labels: UI Components

#189 Adding account buttons `ProfileView`
  GravatarUI.podspec
  Sources/GravatarUI/Bundle+ResourceBundle.swift
  Sources/GravatarUI/Configurator/Configurators.swift
  Sources/GravatarUI/ProfileFields/AccountButtonBuilder.swift
  Sources/GravatarUI/ProfileFields/Model/AccountModel.swift
  Sources/GravatarUI/ProfileFields/ProfileButtonBuilder.swift
  Sources/GravatarUI/ProfileView/LargeProfileView.swift
  Sources/GravatarUI/ProfileView/ProfileComponentView.swift
  Sources/GravatarUI/ProfileView/ProfileSummaryView.swift
  Sources/GravatarUI/ProfileView/ProfileView.swift
  Sources/GravatarUI/Resources/AccountIcons.xcassets/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/calendly.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/calendly.imageset/calendly.pdf
  Sources/GravatarUI/Resources/AccountIcons.xcassets/fediverse.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/fediverse.imageset/fediverse.pdf
  Sources/GravatarUI/Resources/AccountIcons.xcassets/foursquare.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/foursquare.imageset/foursquare.pdf
  Sources/GravatarUI/Resources/AccountIcons.xcassets/github.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/github.imageset/github.pdf
  Sources/GravatarUI/Resources/AccountIcons.xcassets/gravatar.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/gravatar.imageset/gravatar.pdf
  Sources/GravatarUI/Resources/AccountIcons.xcassets/instagram.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/instagram.imageset/instagram.pdf
  Sources/GravatarUI/Resources/AccountIcons.xcassets/mastodongeneric.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/mastodongeneric.imageset/mastodongeneric.pdf
  Sources/GravatarUI/Resources/AccountIcons.xcassets/stackoverflow.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/stackoverflow.imageset/stackoverflow.pdf
  Sources/GravatarUI/Resources/AccountIcons.xcassets/tiktok.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/tiktok.imageset/tiktok.pdf
  Sources/GravatarUI/Resources/AccountIcons.xcassets/tripit.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/tripit.imageset/tripit.pdf
  Sources/GravatarUI/Resources/AccountIcons.xcassets/tumblr.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/tumblr.imageset/tumblr.pdf
  Sources/GravatarUI/Resources/AccountIcons.xcassets/twitch.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/twitch.imageset/twitch.pdf
  Sources/GravatarUI/Resources/AccountIcons.xcassets/twitter-alt.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/twitter-alt.imageset/twitter-alt.pdf
  Sources/GravatarUI/Resources/AccountIcons.xcassets/vimeo.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/vimeo.imageset/vimeo.pdf
  Sources/GravatarUI/Resources/AccountIcons.xcassets/wordpress.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/wordpress.imageset/wordpress.pdf
  Tests/GravatarUITests/LargeProfileViewTests.swift
  Tests/GravatarUITests/__Snapshots__/ProfileViewTests/testProfileView.dark.png
  Tests/GravatarUITests/__Snapshots__/ProfileViewTests/testProfileView.light.png
Labels: UI Components

#194 Implementing UIContentConfiguration for ProfileView and ProfileSummaryView
  Demo/Demo/Gravatar-Demo/DemoProfileConfigurationViewController.swift
  Demo/Demo/Gravatar-Demo/MainTableViewController.swift
  Demo/Gravatar-Demo.xcodeproj/project.pbxproj
  Sources/GravatarUI/ProfileFields/Model/PersonalInfoModel.swift
  Sources/GravatarUI/ProfileView/LargeProfileSummaryView.swift
  Sources/GravatarUI/ProfileView/LargeProfileView.swift
  Sources/GravatarUI/ProfileView/ProfileSummaryView.swift
  Sources/GravatarUI/ProfileView/ProfileView.swift
  Sources/GravatarUI/ProfileView/ProfileViewConfiguration.swift
  Tests/GravatarUITests/LargeProfileSummaryViewTests.swift
Labels: UI Components

#196 Set icon size programmatically so that we don't need to manually adjust pdf icon sizes
  Sources/GravatarUI/ProfileView/ProfileComponentView.swift
  Sources/GravatarUI/ProfileView/ProfileView.swift
  Sources/GravatarUI/Resources/AccountIcons.xcassets/calendly.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/fediverse.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/foursquare.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/github.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/gravatar.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/instagram.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/mastodongeneric.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/stackoverflow.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/tiktok.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/tripit.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/tumblr.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/twitch.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/twitter-alt.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/vimeo.imageset/Contents.json
  Sources/GravatarUI/Resources/AccountIcons.xcassets/wordpress.imageset/Contents.json
  Tests/GravatarUITests/__Snapshots__/ProfileViewTests/testProfileView.dark.png
  Tests/GravatarUITests/__Snapshots__/ProfileViewTests/testProfileView.light.png
Labels: enhancement

#204 Configure profile view margins with `ProfileViewConfiguration`
  Sources/GravatarUI/ProfileView/ProfileComponentView.swift
  Sources/GravatarUI/ProfileView/ProfileSummaryView.swift
  Sources/GravatarUI/ProfileView/ProfileView.swift
  Sources/GravatarUI/ProfileView/ProfileViewConfiguration.swift
  Tests/GravatarUITests/TestProfileConfiguration.swift
  Tests/GravatarUITests/__Snapshots__/ProfileViewTests/testProfileView.dark.png
  Tests/GravatarUITests/__Snapshots__/ProfileViewTests/testProfileView.light.png
Labels: UI Components

#206 Removing custom font sizes
  Sources/GravatarUI/DesignSystem/UIFont+DesignSystem.swift
  Sources/GravatarUI/ProfileFields/DisplayNameBuilder.swift
  Sources/GravatarUI/ProfileView/ProfileSummaryView.swift
  Sources/GravatarUI/ProfileView/ProfileView.swift
  Tests/GravatarUITests/__Snapshots__/AboutMeBuilderTests/testAboutMe.testAboutMe-Dark.png
  Tests/GravatarUITests/__Snapshots__/AboutMeBuilderTests/testAboutMe.testAboutMe-Light.png
  Tests/GravatarUITests/__Snapshots__/AboutMeBuilderTests/testAboutMeWithSmallWidth.1.png
  Tests/GravatarUITests/__Snapshots__/DisplayNameBuilderTests/testDisplayNameField.testDisplayNameField-Dark.png
  Tests/GravatarUITests/__Snapshots__/DisplayNameBuilderTests/testDisplayNameField.testDisplayNameField-Light.png
  Tests/GravatarUITests/__Snapshots__/DisplayNameBuilderTests/testDisplayNameFieldWithMissingDisplayName.testDisplayNameFieldWithMissingDisplayName-Dark.png
  Tests/GravatarUITests/__Snapshots__/DisplayNameBuilderTests/testDisplayNameFieldWithMissingDisplayName.testDisplayNameFieldWithMissingDisplayName-Light.png
  Tests/GravatarUITests/__Snapshots__/DisplayNameBuilderTests/testDisplayNameFieldWithMissingNames.testDisplayNameFieldWithMissingNames-Dark.png
  Tests/GravatarUITests/__Snapshots__/DisplayNameBuilderTests/testDisplayNameFieldWithMissingNames.testDisplayNameFieldWithMissingNames-Light.png
  Tests/GravatarUITests/__Snapshots__/DisplayNameBuilderTests/testDisplayNameFieldWithSmallWidth.1.png
  Tests/GravatarUITests/__Snapshots__/LargeProfileSummaryViewTests/testLargeProfileSummaryView.dark.png
  Tests/GravatarUITests/__Snapshots__/LargeProfileSummaryViewTests/testLargeProfileSummaryView.light.png
  Tests/GravatarUITests/__Snapshots__/LargeProfileViewTests/testLargeProfileView.testLargeProfileView-Dark.png
  Tests/GravatarUITests/__Snapshots__/LargeProfileViewTests/testLargeProfileView.testLargeProfileView-Light.png
  Tests/GravatarUITests/__Snapshots__/PersonalInfoBuilderTests/testPersonalInfoCustom.testPersonalInfoFull-Dark.png
  Tests/GravatarUITests/__Snapshots__/PersonalInfoBuilderTests/testPersonalInfoCustom.testPersonalInfoFull-Light.png
  Tests/GravatarUITests/__Snapshots__/PersonalInfoBuilderTests/testPersonalInfoFull.testPersonalInfoFull-Dark.png
  Tests/GravatarUITests/__Snapshots__/PersonalInfoBuilderTests/testPersonalInfoFull.testPersonalInfoFull-Light.png
  Tests/GravatarUITests/__Snapshots__/PersonalInfoBuilderTests/testPersonalInfoWithSmallWidth.1.png
  Tests/GravatarUITests/__Snapshots__/ProfileSummaryViewTests/testProfileSummaryView.dark.png
  Tests/GravatarUITests/__Snapshots__/ProfileSummaryViewTests/testProfileSummaryView.light.png
  Tests/GravatarUITests/__Snapshots__/ProfileViewTests/testProfileView.dark.png
  Tests/GravatarUITests/__Snapshots__/ProfileViewTests/testProfileView.light.png
Labels: UI Components

#215 Fix alignments on standard profile views
  Sources/GravatarUI/ProfileView/ProfileSummaryView.swift
  Sources/GravatarUI/ProfileView/ProfileView.swift
  Tests/GravatarUITests/__Snapshots__/ProfileSummaryViewTests/testProfileSummaryView.dark.png
  Tests/GravatarUITests/__Snapshots__/ProfileSummaryViewTests/testProfileSummaryView.light.png
  Tests/GravatarUITests/__Snapshots__/ProfileViewTests/testProfileView.dark.png
  Tests/GravatarUITests/__Snapshots__/ProfileViewTests/testProfileView.light.png
Labels: UI Components

#220 Fix extra dot separator with pronouns only model
  Sources/GravatarUI/ProfileFields/Model/PersonalInfoModel.swift
  Sources/GravatarUI/ProfileFields/PersonalInfoField.swift
  Sources/GravatarUI/ProfileView/LargeProfileSummaryView.swift
  Tests/GravatarUITests/PersonalInfoBuilderTests.swift
Labels: bug, UI Components

#214 Adding profile view buttons action delegate
  Demo/Demo/Gravatar-Demo/DemoLargeProfileViewController.swift
  Demo/Demo/Gravatar-Demo/DemoProfileConfigurationViewController.swift
  Sources/GravatarUI/ProfileFields/Model/AccountModel.swift
  Sources/GravatarUI/ProfileFields/Model/ProfileMetadataModel.swift
  Sources/GravatarUI/ProfileFields/Model/ProfileModel.swift
  Sources/GravatarUI/ProfileView/BaseProfileView.swift
  Sources/GravatarUI/ProfileView/LargeProfileSummaryView.swift
  Sources/GravatarUI/ProfileView/LargeProfileView.swift
  Sources/GravatarUI/ProfileView/ProfileSummaryView.swift
  Sources/GravatarUI/ProfileView/ProfileView.swift
  Sources/GravatarUI/ProfileView/ProfileViewConfiguration.swift
  Tests/GravatarUITests/LargeProfileViewTests.swift
  Tests/GravatarUITests/ProfileButtonsActionsTests.swift
Labels: UI Components

#219 Adding edit profile button style
  Demo/Demo/Gravatar-Demo/DemoLargeProfileViewController.swift
  Sources/GravatarUI/ProfileFields/Model/ProfileMetadataModel.swift
  Sources/GravatarUI/ProfileFields/ProfileButtonBuilder.swift
  Sources/GravatarUI/ProfileView/BaseProfileView.swift
  Sources/GravatarUI/ProfileView/LargeProfileSummaryView.swift
  Sources/GravatarUI/ProfileView/LargeProfileView.swift
  Sources/GravatarUI/ProfileView/ProfileSummaryView.swift
  Sources/GravatarUI/ProfileView/ProfileView.swift
  Sources/GravatarUI/ProfileView/ProfileViewConfiguration.swift
  Tests/GravatarUITests/LargeProfileViewTests.swift
  Tests/GravatarUITests/ProfileButtonTests.swift
  Tests/GravatarUITests/ProfileConfigurationTests.swift
  Tests/GravatarUITests/__Snapshots__/ProfileButtonTests/testProfileButtonSnapshots.edit.png
  Tests/GravatarUITests/__Snapshots__/ProfileButtonTests/testProfileButtonSnapshots.view.png
Labels: UI Components

#232 Refactor image cache
  Sources/Gravatar/Cache/ImageCaching.swift
  Sources/Gravatar/Network/ImageDownloadResult.swift
  Sources/Gravatar/Network/Services/HTTPClient.swift
  Sources/Gravatar/Network/Services/ImageDownloadService.swift
  Sources/Gravatar/Network/URLSessionProtocol.swift
  Sources/Gravatar/UIImage/Processor/ImageProcessor.swift
  Tests/GravatarTests/GravatarImageCacheTests.swift
  Tests/GravatarTests/ImageDownloadServiceTests.swift
  Tests/GravatarTests/TestImageCache.swift
  Tests/GravatarTests/TestImageProcessor.swift
  Tests/GravatarTests/TestURLSession.swift
  Tests/GravatarTests/URLSessionMock.swift
  Tests/GravatarUITests/TestImageCache.swift
  Tests/GravatarUITests/TestImageProcessor.swift
  Tests/GravatarUITests/URLSessionMock.swift
Labels: Concurrency

#229 GravatarUI docc bundle
  .spi.yml
  Makefile
  Sources/Gravatar/Gravatar.docc/Gravatar.md
  Sources/GravatarUI/GravatarUI.docc/GravatarUI.md
  Sources/GravatarUI/GravatarUI.docc/Resources/ProfileExamples/largeProfileSummaryView.view@2x.png
  Sources/GravatarUI/GravatarUI.docc/Resources/ProfileExamples/largeProfileSummaryView.view~dark@2x.png
  Sources/GravatarUI/GravatarUI.docc/Resources/ProfileExamples/largeProfileView.view@2x.png
  Sources/GravatarUI/GravatarUI.docc/Resources/ProfileExamples/largeProfileView.view~dark@2x.png
  Sources/GravatarUI/GravatarUI.docc/Resources/ProfileExamples/profileSummaryView.view@2x.png
  Sources/GravatarUI/GravatarUI.docc/Resources/ProfileExamples/profileSummaryView.view~dark@2x.png
  Sources/GravatarUI/GravatarUI.docc/Resources/ProfileExamples/profileView.view@2x.png
  Sources/GravatarUI/GravatarUI.docc/Resources/ProfileExamples/profileView.view~dark@2x.png
  Sources/GravatarUI/GravatarUI.docc/Resources/gravatar-sdk@2x.png
  Sources/GravatarUI/ProfileView/LargeProfileSummaryView.swift
  Sources/GravatarUI/ProfileView/LargeProfileView.swift
  Sources/GravatarUI/ProfileView/ProfileSummaryView.swift
  Sources/GravatarUI/ProfileView/ProfileView.swift
  Tests/GravatarUITests/ImageHelper.swift
  Tests/GravatarUITests/ProvileViewSnapshots.swift
  Tests/GravatarUITests/Resources/example_avatar.png
  Tests/GravatarUITests/__Snapshots__/ProvileViewSnapshots/largeProfileSummaryView.view-dark.png
  Tests/GravatarUITests/__Snapshots__/ProvileViewSnapshots/largeProfileSummaryView.view.png
  Tests/GravatarUITests/__Snapshots__/ProvileViewSnapshots/largeProfileView.view-dark.png
  Tests/GravatarUITests/__Snapshots__/ProvileViewSnapshots/largeProfileView.view.png
  Tests/GravatarUITests/__Snapshots__/ProvileViewSnapshots/profileSummaryView.view-dark.png
  Tests/GravatarUITests/__Snapshots__/ProvileViewSnapshots/profileSummaryView.view.png
  Tests/GravatarUITests/__Snapshots__/ProvileViewSnapshots/profileView.view-dark.png
  Tests/GravatarUITests/__Snapshots__/ProvileViewSnapshots/profileView.view.png
Labels: documentation

#235 Re-export Gravatar
  Demo/Demo/Gravatar-Demo/DemoBaseProfileViewController.swift
  Demo/Demo/Gravatar-Demo/DemoProfileConfigurationViewController.swift
  Demo/Demo/Gravatar-Demo/DemoProfilePresentationStylesViewController.swift
  Demo/Demo/Gravatar-Demo/DemoProfileViewsViewController.swift
  Demo/Demo/Gravatar-Demo/DemoUIImageViewExtensionViewController.swift
  Sources/GravatarUI/Exports.swift
  Sources/GravatarUI/RenameMe.swift
  Tests/GravatarUITests/AboutMeBuilderTests.swift
  Tests/GravatarUITests/DisplayNameBuilderTests.swift
  Tests/GravatarUITests/GravatarWrapper+UIImageViewTests.swift
  Tests/GravatarUITests/LargeProfileSummaryViewTests.swift
  Tests/GravatarUITests/LargeProfileViewTests.swift
  Tests/GravatarUITests/PersonalInfoBuilderTests.swift
  Tests/GravatarUITests/ProfileButtonsActionsTests.swift
  Tests/GravatarUITests/ProfileSummaryViewTests.swift
  Tests/GravatarUITests/ProfileViewTests.swift
  Tests/GravatarUITests/TestActivityIndicator.swift
  Tests/GravatarUITests/TestImageFetcher.swift
  Tests/GravatarUITests/TestImageProcessor.swift
  Tests/GravatarUITests/TestPlaceholderDisplayers.swift
Labels: enhancement
