Repository Automattic/Gravatar-SDK-iOS, pull requests merged in 2025-01, with the labels that each got.

#614 Quick Editor: Update the intro screen
  Sources/Gravatar/BundleInfo.swift
  Sources/GravatarUI/Resources/Media.xcassets/qe-intro-empty-profile-avatar.imageset/Avatar 1.svg
  Sources/GravatarUI/Resources/Media.xcassets/qe-intro-empty-profile-avatar.imageset/Avatar.svg
  Sources/GravatarUI/Resources/Media.xcassets/qe-intro-empty-profile-avatar.imageset/Contents.json
  Sources/GravatarUI/Resources/en.lproj/Localizable.strings
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerProfileView.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerProfileViewWrapper.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerView.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerViewModel.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/Views/ContentLoadingErrorView.swift
  Sources/GravatarUI/SwiftUI/ProfileEditor/QuickEditor.swift
  Sources/GravatarUI/SwiftUI/ProfileEditor/QuickEditorNoticeView.swift
  Tests/GravatarUITests/AvatarPickerProfileViewTests.swift
  Tests/GravatarUITests/__Snapshots__/AvatarPickerProfileViewTests/testAvatarPickerProfileView.1.png
  Tests/GravatarUITests/__Snapshots__/AvatarPickerProfileViewTests/testAvatarPickerProfileView.2.png
  Tests/GravatarUITests/__Snapshots__/AvatarPickerProfileViewTests/testAvatarPickerProfileViewEmpty.1.png
  Tests/GravatarUITests/__Snapshots__/AvatarPickerProfileViewTests/testAvatarPickerProfileViewEmpty.2.png
Labels: enhance, [Feature] Gravatar-QuickEditor, [Priority] Medium

#620 Responding to deny button app on web oauth
  Sources/GravatarUI/SwiftUI/OAuthSession/OAuthSession.swift
Labels: bug, [Priority] Medium

#623 Fix "Multiple images are selected when the same image is uploaded"
  Sources/Gravatar/Resources/SDKInfo.plist
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarGridModel.swift
  Tests/GravatarUITests/AvatarGridModelTests.swift
  version.rb
Labels: bug, [Feature] Gravatar-QuickEditor, [Priority] High

#624 Merge 3.1.1 back to trunk
  Sources/Gravatar/Resources/SDKInfo.plist
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarGridModel.swift
  Tests/GravatarUITests/AvatarGridModelTests.swift
  version.rb
Labels: release

#552 Support for oauth callback https for iOS 17.4 +
  Sources/Gravatar/Configuration.swift
  Sources/GravatarUI/SwiftUI/OAuthSession/OAuthSession.swift
  Sources/GravatarUI/SwiftUI/OAuthSession/OldAuthenticationSession.swift
  Tests/GravatarUITests/OAuthSessionTests.swift
Labels: Tech Debt, [Feature] Gravatar-QuickEditor, [Priority] Medium

#627 Fix MainActor isolation related concurrency warnings
  Sources/GravatarUI/QuickEditor/QuickEditorViewController.swift
  Sources/GravatarUI/SwiftUI/AvatarPickerModalPresentationModifier.swift
Labels: Concurrency, Tech Debt, [Feature] Gravatar-QuickEditor, [Priority] Medium

#629 Set demo app min iOS deployment target to 15.0
  Demo/Demo/Gravatar-Demo/DemoQuickEditorViewController.swift
  Demo/Demo/Gravatar-Demo/SwiftUI/ContentView.swift
  Demo/Demo/Gravatar-Demo/SwiftUI/DemoAvatarPickerView.swift
  Demo/Demo/Gravatar-Demo/SwiftUI/DemoAvatarView.swift
  Demo/Demo/Gravatar-Demo/SwiftUI/DemoProfileEditorView.swift
  Demo/Demo/Gravatar-Demo/SwiftUI/QEColorSchemePickerRow.swift
  Demo/Demo/Gravatar-Demo/SwiftUI/View+Demo.swift
  Demo/Gravatar-Demo.xcodeproj/project.pbxproj
Labels: enhance, demoapp, [Priority] Medium

#632 Fix color scheme on the alt text view
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerView.swift
  Sources/GravatarUI/SwiftUI/View+Additions.swift
Labels: bug, [Feature] Gravatar-QuickEditor, [Priority] Medium

#610 Set Swift 6 as the minimum build tools version
  Demo/Demo/Base.xcconfig
  Package.swift
Labels: bug, enhance

#635 Release 3.2.0-rc.1
  Sources/Gravatar/Resources/SDKInfo.plist
  Sources/GravatarUI/Resources/ar.lproj/Localizable.strings
  Sources/GravatarUI/Resources/de.lproj/Localizable.strings
  Sources/GravatarUI/Resources/es.lproj/Localizable.strings
  Sources/GravatarUI/Resources/fr.lproj/Localizable.strings
  Sources/GravatarUI/Resources/he.lproj/Localizable.strings
  Sources/GravatarUI/Resources/id.lproj/Localizable.strings
  Sources/GravatarUI/Resources/it.lproj/Localizable.strings
  Sources/GravatarUI/Resources/ja.lproj/Localizable.strings
  Sources/GravatarUI/Resources/ko.lproj/Localizable.strings
  Sources/GravatarUI/Resources/nl.lproj/Localizable.strings
  Sources/GravatarUI/Resources/pt-BR.lproj/Localizable.strings
  Sources/GravatarUI/Resources/ru.lproj/Localizable.strings
  Sources/GravatarUI/Resources/sv.lproj/Localizable.strings
  Sources/GravatarUI/Resources/tr.lproj/Localizable.strings
  Sources/GravatarUI/Resources/zh-Hans.lproj/Localizable.strings
  Sources/GravatarUI/Resources/zh-Hant.lproj/Localizable.strings
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerView.swift
  version.rb
Labels: release

#634 Moving SwiftLint and SwiftFormat to Docker
  .buildkite/pipeline.yml
  .buildkite/shared-pipeline-vars
  .swiftformat
  .swiftlint.yml
  Makefile
  Package.resolved
  Package.swift
Labels: Tech Debt

#638 Merge release 3.2.0-rc1 to trunk
  .buildkite/pipeline.yml
  .buildkite/shared-pipeline-vars
  .swiftformat
  .swiftlint.yml
  Makefile
  Package.resolved
  Package.swift
  Sources/Gravatar/Resources/SDKInfo.plist
  Sources/GravatarUI/Resources/ar.lproj/Localizable.strings
  Sources/GravatarUI/Resources/de.lproj/Localizable.strings
  Sources/GravatarUI/Resources/es.lproj/Localizable.strings
  Sources/GravatarUI/Resources/fr.lproj/Localizable.strings
  Sources/GravatarUI/Resources/he.lproj/Localizable.strings
  Sources/GravatarUI/Resources/id.lproj/Localizable.strings
  Sources/GravatarUI/Resources/it.lproj/Localizable.strings
  Sources/GravatarUI/Resources/ja.lproj/Localizable.strings
  Sources/GravatarUI/Resources/ko.lproj/Localizable.strings
  Sources/GravatarUI/Resources/nl.lproj/Localizable.strings
  Sources/GravatarUI/Resources/pt-BR.lproj/Localizable.strings
  Sources/GravatarUI/Resources/ru.lproj/Localizable.strings
  Sources/GravatarUI/Resources/sv.lproj/Localizable.strings
  Sources/GravatarUI/Resources/tr.lproj/Localizable.strings
  Sources/GravatarUI/Resources/zh-Hans.lproj/Localizable.strings
  Sources/GravatarUI/Resources/zh-Hant.lproj/Localizable.strings
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerView.swift
  version.rb
Labels: release

#639 Add docker check
  Makefile
Labels: bug, tooling

#641 Remove unused lane that duplicated existing one
  fastlane/Fastfile
Labels: tooling

#643 Add CI check to validate package.resolved
  .buildkite/pipeline.yml
  Demo/Gravatar-Demo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Makefile
  fastlane/Fastfile
Labels: CI/CD

#615 Extra profile refresh for the new users
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerViewModel.swift
  Tests/GravatarUITests/AvatarPickerViewModelTests.swift
Labels: bug, [Feature] Gravatar-QuickEditor, [Priority] Low

#647 Adds `rating: .x` to the avatar URL in the QE's profile card and some demo screens
  Demo/Demo/Gravatar-Demo/DemoQuickEditorViewController.swift
  Demo/Demo/Gravatar-Demo/SwiftUI/DemoProfileEditorView.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerProfileView.swift
Labels: bug, [Feature] Gravatar-QuickEditor, [Priority] Medium

#652 Fix inconsistencies with android
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerProfileView.swift
  Sources/GravatarUI/SwiftUI/ProfileEditor/QuickEditorNoticeView.swift
  Tests/GravatarUITests/__Snapshots__/AvatarPickerProfileViewTests/testAvatarPickerProfileView.1.png
  Tests/GravatarUITests/__Snapshots__/AvatarPickerProfileViewTests/testAvatarPickerProfileView.2.png
  Tests/GravatarUITests/__Snapshots__/AvatarPickerProfileViewTests/testAvatarPickerProfileViewEmpty.1.png
  Tests/GravatarUITests/__Snapshots__/AvatarPickerProfileViewTests/testAvatarPickerProfileViewEmpty.2.png
Labels: [Feature] Gravatar-QuickEditor, [Priority] Medium

#645 Refactor package.resovled check
  .buildkite/pipeline.yml
  .buildkite/shared-pipeline-vars
  Dangerfile
  Gemfile
  Gemfile.lock
  Makefile
  fastlane/Fastfile
Labels: CI/CD, tooling

#653 Leaving only location on QE profile card details
  Sources/GravatarUI/ProfileFields/Model/PersonalInfoModel.swift
  Sources/GravatarUI/Resources/en.lproj/Localizable.strings
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerProfileView.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerViewModel.swift
  Tests/GravatarUITests/AvatarPickerProfileViewTests.swift
  Tests/GravatarUITests/__Snapshots__/AvatarPickerProfileViewTests/testAvatarPickerProfileView.1.png
  Tests/GravatarUITests/__Snapshots__/AvatarPickerProfileViewTests/testAvatarPickerProfileView.2.png
  Tests/GravatarUITests/__Snapshots__/AvatarPickerProfileViewTests/testAvatarPickerProfileViewEmpty.1.png
  Tests/GravatarUITests/__Snapshots__/AvatarPickerProfileViewTests/testAvatarPickerProfileViewEmpty.2.png
  Tests/GravatarUITests/__Snapshots__/AvatarPickerProfileViewTests/testAvatarPickerProfileViewWithoutLocation.1.png
  Tests/GravatarUITests/__Snapshots__/AvatarPickerProfileViewTests/testAvatarPickerProfileViewWithoutLocation.2.png
Labels: [Feature] Gravatar-QuickEditor, [Priority] Medium

#648 Improve demo app UI
  Demo/Demo/Gravatar-Demo/Common/BaseFormViewController.swift
  Demo/Demo/Gravatar-Demo/Common/FormFields/ButtonField.swift
  Demo/Demo/Gravatar-Demo/Common/FormFields/ButtonLabelField.swift
  Demo/Demo/Gravatar-Demo/Common/FormFields/ImageFormField.swift
  Demo/Demo/Gravatar-Demo/Common/FormFields/LabelField.swift
  Demo/Demo/Gravatar-Demo/Common/FormFields/SegmentedControlField.swift
  Demo/Demo/Gravatar-Demo/Common/FormFields/SwitchField.swift
  Demo/Demo/Gravatar-Demo/Common/FormFields/TextFormField.swift
  Demo/Demo/Gravatar-Demo/DemoAvatarDownloadViewController.swift
  Demo/Demo/Gravatar-Demo/DemoFetchProfileViewController.swift
  Demo/Demo/Gravatar-Demo/DemoUIImageViewExtensionViewController.swift
  Demo/Demo/Gravatar-Demo/DemoUploadImageViewController.swift
  Demo/Gravatar-Demo.xcodeproj/project.pbxproj
  Demo/Gravatar-Demo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Sources/Gravatar/Options/AvatarSelection.swift
Labels: enhance, [Priority] Low

#655 Update localizations
  Sources/GravatarUI/Resources/de.lproj/Localizable.strings
  Sources/GravatarUI/Resources/es.lproj/Localizable.strings
  Sources/GravatarUI/Resources/fr.lproj/Localizable.strings
  Sources/GravatarUI/Resources/he.lproj/Localizable.strings
  Sources/GravatarUI/Resources/id.lproj/Localizable.strings
  Sources/GravatarUI/Resources/ko.lproj/Localizable.strings
  Sources/GravatarUI/Resources/nl.lproj/Localizable.strings
  Sources/GravatarUI/Resources/pt-BR.lproj/Localizable.strings
  Sources/GravatarUI/Resources/ru.lproj/Localizable.strings
  Sources/GravatarUI/Resources/zh-Hans.lproj/Localizable.strings
  Sources/GravatarUI/Resources/zh-Hant.lproj/Localizable.strings
Labels: Localization

#656 Release/3.2.0 backmerge
  .buildkite/pipeline.yml
  .buildkite/shared-pipeline-vars
  Dangerfile
  Demo/Demo/Gravatar-Demo/DemoQuickEditorViewController.swift
  Demo/Demo/Gravatar-Demo/SwiftUI/DemoProfileEditorView.swift
  Gemfile
  Gemfile.lock
  Makefile
  Sources/GravatarUI/Resources/de.lproj/Localizable.strings
  Sources/GravatarUI/Resources/es.lproj/Localizable.strings
  Sources/GravatarUI/Resources/fr.lproj/Localizable.strings
  Sources/GravatarUI/Resources/he.lproj/Localizable.strings
  Sources/GravatarUI/Resources/id.lproj/Localizable.strings
  Sources/GravatarUI/Resources/ko.lproj/Localizable.strings
  Sources/GravatarUI/Resources/nl.lproj/Localizable.strings
  Sources/GravatarUI/Resources/pt-BR.lproj/Localizable.strings
  Sources/GravatarUI/Resources/ru.lproj/Localizable.strings
  Sources/GravatarUI/Resources/zh-Hans.lproj/Localizable.strings
  Sources/GravatarUI/Resources/zh-Hant.lproj/Localizable.strings
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerProfileView.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerView.swift
  Sources/GravatarUI/SwiftUI/AvatarPicker/AvatarPickerViewModel.swift
  Sources/GravatarUI/SwiftUI/AvatarView.swift
  Sources/GravatarUI/SwiftUI/CachedAsyncImage.swift
  Tests/GravatarUITests/AvatarPickerViewModelTests.swift
Labels: release
