Repository Automattic/Gravatar-SDK-iOS, pull requests merged in 2025-02, with the labels that each got.

#658 Download localized strings
  Sources/GravatarUI/Resources/ar.lproj/Localizable.strings
  Sources/GravatarUI/Resources/de.lproj/Localizable.strings
  Sources/GravatarUI/Resources/es.lproj/Localizable.strings
  Sources/GravatarUI/Resources/fr.lproj/Localizable.strings
  Sources/GravatarUI/Resources/he.lproj/Localizable.strings
  Sources/GravatarUI/Resources/id.lproj/Localizable.strings
  Sources/GravatarUI/Resources/it.lproj/Localizable.strings
  Sources/GravatarUI/Resources/ja.lproj/Localizable.strings
  Sources/GravatarUI/Resources/ko.lproj/Localizable.strings
  Sources/GravatarUI/Resources/nl.lproj/Localizable.strings
  Sources/GravatarUI/Resources/pt-BR.lproj/Localizable.strings
  Sources/GravatarUI/Resources/ru.lproj/Localizable.strings
  Sources/GravatarUI/Resources/sv.lproj/Localizable.strings
  Sources/GravatarUI/Resources/tr.lproj/Localizable.strings
  Sources/GravatarUI/Resources/zh-Hans.lproj/Localizable.strings
  Sources/GravatarUI/Resources/zh-Hant.lproj/Localizable.strings
Labels: enhance, Localization, [Feature] Gravatar-QuickEditor, [Priority] Medium

#661 Fix CocoaPods Publishing Pipeline
  .buildkite/pipeline.yml
Labels: bug, CI/CD

#662 Simplify SwiftFormat Invocations
  .buildkite/pipeline.yml
  Makefile
Labels: CI/CD, tooling, Tech Debt

#663 Leverage `xcconfig` for App Clip project, too
  Demo/Config/Base.xcconfig
  Demo/Config/Enterprise.xcconfig
  Demo/Demo/Gravatar-Demo/Gravatar-Demo.Release.xcconfig
  Demo/Gravatar-Demo.xcodeproj/project.pbxproj
  fastlane/Fastfile
Labels: enhance
